const destruction = [
  {
    name: 'Black Hole',
    code: 'BLACK_HOLE',
    type: 'DESTRUCTION',
    method: 'black-hole',
    limitted: 1,
    logo: null,
    image: null,
  },
  {
    name: 'Blind',
    code: 'BLIND',
    type: 'DESTRUCTION',
    method: 'blind',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Curse Of The Cat Butt',
    code: 'CURSE-OF-THE-CAT-BUTT',
    type: 'DESTRUCTION',
    method: 'curse-of-the-cat-butt',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Catomic Bomb',
    code: 'CATOMIC-BOMB',
    type: 'DESTRUCTION',
    method: 'catomic-bomb',
    limitted: 1,
    logo: null,
    image: null,
  },
  {
    name: 'Split',
    code: 'SPLIT',
    type: 'DESTRUCTION',
    method: 'split',
    limitted: 2,
    logo: null,
    image: null,
  },
  {
    name: 'Refuse',
    code: 'REFUSE',
    type: 'DESTRUCTION',
    method: 'refuse',
    limitted: 1,
    logo: null,
    image: null,
  },
  {
    name: 'Purfect Boost',
    code: 'PURFECT-BOOST',
    type: 'DESTRUCTION',
    method: 'purfect-boost',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Imploding Kitten',
    code: 'IMPLODING-KITTEN',
    type: 'DESTRUCTION',
    method: 'imploding-kitten',
    limitted: 1,
    logo: null,
    image: null,
  },
]

export default destruction;