const future = [
  {
    name: 'See The Future',
    code: 'SEE-THE-FUTURE-ONE-CARD',
    type: 'FUTURE',
    method: 'see-the-future',
    times: 1,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'See The Future',
    code: 'SEE-THE-FUTURE-THREE-CARD',
    type: 'FUTURE',
    method: 'see-the-future',
    times: 3,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'See The Future',
    code: 'SEE-THE-FUTURE-FIVE-CARD',
    type: 'FUTURE',
    method: 'see-the-future',
    times: 5,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Atler The Future',
    code: 'ALTER-THE-FUTURE-FIVE-CARD',
    type: 'FUTURE',
    method: 'atler-the-future',
    times: 5,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Atler The Future',
    code: 'ALTER-THE-FUTURE-FIVE-CARD',
    type: 'FUTURE',
    method: 'atler-the-future',
    times: 5,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Atler The Future',
    code: 'ALTER-THE-FUTURE-FIVE-CARD',
    type: 'FUTURE',
    method: 'atler-the-future',
    times: 5,
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Create The Future',
    code: 'CREATE-THE-FUTURE-FIVE-CARD',
    type: 'FUTURE',
    method: 'create-the-future',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Garbage Collection',
    code: 'GARBAFE-COLLECTION',
    type: 'FUTURE',
    method: 'garbage-collection',
    limitted: 2,
    logo: null,
    image: null,
  }
]