const attack = [
  {
    name: 'Attack',
    code: 'ATTACK',
    type: 'ATTACK',
    method: 'attack',
    limitted: 6,
    logo: null,
    image: null,
  },
  {
    name: 'Targeted Attack',
    code: 'TARGETED-ATTACK',
    type: 'ATTACK',
    method: 'targeted-attack',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Slap',
    code: 'SLAP-SINGLE',
    type: 'ATTACK',
    method: 'slap',
    times: 1,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Slap',
    code: 'SLAP-DOUBLE',
    type: 'ATTACK',
    method: 'slap',
    times: 2,
    limitted: 2,
    logo: null,
    image: null,
  },
  {
    name: 'Slap',
    code: 'SLAP-TRIPPLE',
    type: 'ATTACK',
    method: 'slap',
    times: 3,
    limitted: 2,
    logo: null,
    image: null,
  },
  {
    name: 'You Have Take That',
    code: 'YOU-HAVE-TAKE-THAT',
    type: 'ATTACK',
    method: 'you-have-take-that',
    limitted: 2,
    logo: null,
    image: null,
  },
  {
    name: 'Last Resort',
    code: 'LAST-RESORT',
    type: 'ATTACK',
    method: 'last-resort',
    limitted: 1,
    logo: null,
    image: null,
  },
  {
    name: 'Annoy',
    code: 'ANNOY',
    type: 'ATTACK',
    method: 'annoy',
    limitted: 3,
    logo: null,
    image: null,
  },
]