const kittens = [
  {
    name: 'Catter Melon',
    code: 'CATTER-MELON',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Tacocat',
    code: 'TACOCAT',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Beardcat',
    code: 'TACOCAT',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Hairy Potato Cat',
    code: 'HAIRY-POTATO-CAT',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Rainbow-Ralphing Cat',
    code: 'RAINBOW-RALPHING-CAT',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Feral Cat',
    code: 'FERAL-CAT',
    type: 'KITTEN',
    method: null,
    limitted: 4,
    logo: null,
    image: null,
  }
]