const defense = [
  {
    name: 'Skip',
    code: 'SKIP',
    type: 'DEFENSE',
    method: 'skip',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Super Skip',
    code: 'SUPER-SKIP',
    type: 'DEFENSE',
    method: 'super-skip',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Exchange',
    code: 'EXCHANGE',
    type: 'DEFENSE',
    method: 'exchange',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Peek',
    code: 'PEEK',
    type: 'DEFENSE',
    method: 'peek',
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Sneak Peek',
    code: 'SNEAK-PEEK',
    type: 'DEFENSE',
    method: 'sneak-peek',
    limitted: 4,
    logo: null,
    image: null,
  },
  {
    name: 'Copy',
    code: 'COPY',
    type: 'DEFENSE',
    method: 'copy',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Discard',
    code: 'DISCARD',
    type: 'DEFENSE',
    method: 'discard',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Mark',
    code: 'MARK',
    type: 'DEFENSE',
    method: 'mark',
    limitted: 5,
    logo: null,
    image: null,
  },
]