const drawing = [
  {
    name: 'Favor',
    code: 'FAVOR',
    type: 'DRAWING',
    method: 'favor',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Steal A Card',
    code: 'STEAL-A-CARD',
    type: 'DRAWING',
    method: 'steal-a-card',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Self Slap',
    code: 'SELF-SLAP-DOUPLE',
    type: 'DRAWING',
    method: 'seft-slap',
    limitted: 5,
    times: 2,
    logo: null,
    image: null,
  },
  {
    name: 'Self Slap',
    code: 'SELF-SLAP-TRIPLE',
    type: 'DRAWING',
    method: 'seft-slap',
    limitted: 5,
    times: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Draw From Anywhere',
    code: 'DRAW-FROM-ANYWHERE',
    type: 'DRAWING',
    method: 'draw-from-anywhere',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Dumpster Dive',
    code: 'DUMPSTER-DIVE',
    type: 'DRAWING',
    method: 'dumpster-dive',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Return',
    code: 'RETURN',
    type: 'DRAWING',
    method: 'return',
    limitted: 3,
    logo: null,
    image: null,
  },
  {
    name: 'Swap Top To Bottom',
    code: 'SWAP-TOP-TO-BOTTOM',
    type: 'DRAWING',
    method: 'swap-top-to-bottom',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Back From The Dead',
    code: 'BACK-FROM-THE-DEAD',
    type: 'DRAWING',
    method: 'back-from-the-dead',
    limitted: 5,
    logo: null,
    image: null,
  },
  {
    name: 'Draw From The Bottom',
    code: 'DRAW-FROM-THE-BOTTOM',
    type: 'DRAWING',
    method: 'draw-from-the-bottom',
    limitted: 5,
    logo: null,
    image: null,
  }
]

export default drawing;